import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <header className='fixed w-full z-50'>
          <div className="navbar bg-base-100">
            <div className="navbar-start">
              <div className="dropdown">
                <label tabIndex={0} className="btn btn-ghost lg:hidden">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
                </label>
                <ul tabIndex={0} className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-60">
                  <li><Link href={'/'}>Home</Link></li>
                  <li><Link href={'/blog'}>Blog</Link></li>
                  <li tabIndex={0}>
                    <details>
                      <summary>Serviços</summary>
                      <ul className="p-2">
                        <li><Link href={'/servicos/desenvolvimento-web'}>Desenvolvimento Web</Link></li>
                        <li><Link href={'/servicos/gestao-redes-sociais'}>Gestão de Redes Sociais</Link></li>
                        <li><Link href={'/servicos/marketing-digital'}>Marketing Digital</Link></li>
                      </ul>
                    </details>
                  </li>
                  <li><Link href={'/portfolio'}>Portfólio</Link></li>
                  <li><Link href={'/contato'}>Contato</Link></li>
                </ul>
              </div>
              <a href='/' className="btn btn-ghost normal-case text-xl">Assis Junior W&M</a>
            </div>
            <div className="navbar-center hidden lg:flex">
              <ul className="menu menu-horizontal px-1">
                <li><Link href={'/'}>Home</Link></li>
                <li><Link href={'/blog'}>Blog</Link></li>
                <li tabIndex={0}>
                  <details>
                    <summary>Serviços</summary>
                    <ul className="p-2">
                      <li><Link href={'/servicos/desenvolvimento-web'}>Desenvolvimento Web</Link></li>
                      <li><Link href={'/servicos/gestao-redes-sociais'}>Gestão de Redes Sociais</Link></li>
                      <li><Link href={'/servicos/marketing-digital'}>Marketing Digital</Link></li>
                    </ul>
                  </details>
                </li>
                <li><Link href={'/portfolio'}>Portfólio</Link></li>
                <li><Link href={'/contato'}>Contato</Link></li>
              </ul>
            </div>
            <div className="navbar-end">
              {/* <a className="btn">Button</a> */}
            </div>
          </div>
        </header>
        {children}
        <footer className="footer p-10 bg-base-200 text-base-content">
          <div>
            <span className="footer-title">Serviços</span> 
              <Link href={'/servicos/desenvolvimento-web'} className="link link-hover">Desenvolvimento Web</Link>
              <Link href={'/servicos/gestao-redes-sociais'} className="link link-hover">Gestão de Redes Sociais</Link>
              <Link href={'/servicos/marketing-digital'} className="link link-hover">Marketing Digital</Link>
          </div> 
          <div>
            <span className="footer-title">Páginas</span> 
            <Link href='/' className="link link-hover">Home</Link> 
            <Link href='/blog' className="link link-hover">Blog</Link> 
            <Link href='/servicos' className="link link-hover">Serviços</Link> 
            <Link href={'/portfolio'}>Portfólio</Link>
            <Link href='/contato' className="link link-hover">Contato</Link>
          </div> 
          <div>
            <span className="footer-title">Políticas</span> 
            <a className="link link-hover">Termos de uso</a> 
            <a className="link link-hover">Política de Privacidade</a> 
            <a className="link link-hover">Política de Cookies</a>
          </div> 
          <div>
            <span className="footer-title">Newsletter</span> 
            <div className="form-control w-80">
              <label className="label">
                <span className="label-text">Digite seu endereço de E-mail</span>
              </label> 
              <div className="relative">
                <input type="email" placeholder="username@site.com" className="input input-bordered w-full pr-16" /> 
                <button className="btn btn-primary absolute top-0 right-0 rounded-l-none">Assinar</button>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  )
}
